### ISSUE TITLE
module 'metrics.LPIPS' has no attribute 'models'

### ISSUE THREAD

**Issue by marchage** [skycrapers/TecoGAN-PyTorch#1]
Hi, 

Nice project!

I had to change line 15 in file ./codes/metrics/LPIPS/models/networks_basic.py from
`import metrics.LPIPS.models as util`
to 
`import models as util`
to get it to run. But I am not a python guy so to speak, so perhaps I did it wrong. Hope this helps.

**Comment by marchage** [comment]
But maybe this was because I was using python 3. And perhaps you intended it to run on python 2. (I changed the test bash script call to python as well to call it via python3).

**Comment by jndeng** [comment]
Hi, @marchage 
Thanks for your interest! 

What error did you encounter when using `import metrics.LPIPS.models as util`? I was also using python 3 and it works for me. 

There are actually two packages named `models`. If you change to `import models as util`, you may not be able to evaluate the results with metric LPIPS.

**Comment by marchage** [comment]
Hi @jndeng! Aah - whoops - I guess I overlooked that in my haste.

My error message is "AttributeError: module 'metrics.LPIPS' has no attribute 'models'". (in networks_basic.py line 15, sorry had to type it over so I don't have the entire stack trace).

**Comment by jndeng** [comment]
Hi @marchage
I just tried it again and it still works fine for me. Maybe it's due to the python version issue? I was testing on python 3.7.4

Based on your error message, I think the problem was caused when importing the third-party package LPIPS. In fact, my current solution to import this package is quite ad-hoc.
I think I will find a better way later.

**Comment by mjc619** [comment]
I can confirm that you need 3.7.4 for LPIPS to seem to work and a version of scikit-image >.18 due to a depreciation of measure.ssim to metrics.structural_similarity.
also some of TensorFlow's dependencies are still required to run, if someone opens anything up later with a bug.

**Comment by IceClear** [comment]
I have the same problem under python 3.6.13. However, reinstall a new python env is somehow a little complex. I think change `import metrics.LPIPS.models as util` to `from metrics.LPIPS import models as util` solves the problem.
