### ISSUE TITLE
What about degradation settings of BD?

### ISSUE THREAD

**Issue by mrluin** [skycrapers/TecoGAN-PyTorch#10]
Hi,

Thanks for your great reimplementation!

I saw that degradation type indeed had big impact on the super-resolution result, especially in vid4-calendar and vid4-foliage, so what about the degradation setting of BD, the link given in readme was broken down~

Looking forward to your reply :)

**Comment by jndeng** [comment]
Hi, thanks for your interest!

Actually, I was planning to write a wiki about the details of this two degradation types, and the differences between them, but somehow I forgot.

You can find the code of BD degradation [here](https://github.com/skycrapers/TecoGAN-PyTorch/blob/master/codes/data/__init__.py#L87). Basically it does two things. First it blurs the whole HR image with Gaussian kernel, and then samples the blurred image every four pixels.

**Comment by mrluin** [comment]
Thanks for your help!

But when I tried to using code from [resize_BD.py](https://github.com/skycrapers/TecoGAN-PyTorch/blob/master/scripts/resize_BD.py), it seems that cv2 cannot work well with multiprocessing, `cv2.GaussianBlur` did not work in processing, and thus there was no degraded LR data saved.

Do you have any suggestions?
