### ISSUE TITLE
Training plots of losses

### ISSUE THREAD

**Issue by bfreskura** [skycrapers/TecoGAN-PyTorch#12]
Hi,

Could you provide training plots of all losses? I've implemented my own version of TecoGAN that was influenced by this repo, but I can't figure out if I'm getting the best results as my losses don't seem to be decreasing.

**Comment by jndeng** [comment]
Hi, I've uploaded my plots of the training losses [here](https://drive.google.com/file/d/1Pt8B1hdUdGK1HGdegd2RcFz2Kq3RNMFp/view?usp=sharing). In my case, these losses did not converge either, just like other GAN training.

My suggestion to find a best model is to test on a validation dataset, and then visually compare the results produced by different models.

**Comment by bfreskura** [comment]
It seems the GDrive link has restricted access. Can you make it public so people can see the file without requiring permissions first?

**Comment by jndeng** [comment]
oh, I forgot to make it public. It's done now.
