### ISSUE TITLE
Full name of BI and BD degradation?

### ISSUE THREAD

**Issue by xuanquang1999** [skycrapers/TecoGAN-PyTorch#17]
Hi,

I want to ask about what exactly does BI and BD stand for. Does BI stand for Bicubic Interpolation and BD stand for Bicubic Downsampling?

Thanks

**Comment by momalave** [comment]
BD is "Gaussian/Blur Downscale", BI is "Bicubic" downscale, and DN is "Downscale Noise". Hope this helps.
