### ISSUE TITLE
Did you implement Unpaired Video Translation task?

### ISSUE THREAD

**Issue by zhanghm1995** [skycrapers/TecoGAN-PyTorch#18]
Hi, thanks for your wonderful work to reimplement the TecoGAN in Pytorch. I wonder whether you have implemented the Unpaired Video Translation task just like what the paper said?

**Comment by jndeng** [comment]
Sorry, I am not familiar with the unpaired video translation task. I think it has not been implemented in the official TecoGAN repository yet. You may need to find another open-source approach for the unpaired video translation task.

**Comment by zhanghm1995** [comment]
OK，thanks for your explanation.
