### ISSUE TITLE
 Is it normal that only 6gb of 12gb gpu memory is used when upscaled? 

### ISSUE THREAD

**Issue by CybotDNA** [skycrapers/TecoGAN-PyTorch#19]
Super cool project and thanks for sharing :-) 

Is it normal that only 6gb of 12gb gpu memory is used when upscaled? 
And that the clock frequency fluctuates and is not going through to full load?

In the code I tried to increase the number of workers, but there is no difference, is there another place where I can set something? And is the Multi GPU support only for training, or also for upscaling?

I hope you find the time to answer my question, I would be very happy to click, 
Even if I know that you have provided everything free of charge :-)

**Comment by jndeng** [comment]
Hey, thanks for your interest in our project.

Yes, it's normal to use 6GB GPU memory when testing the model. Both the memory and frequency fluctuate are related to the resolutions of the input videos. If the video is large, data loading will take a lot of time and become a bottleneck. Currently, I don't think we can solve this problem.

As for Multi GPUs, it is supported for both training and testing.
