### ISSUE TITLE
How to continue training from a checkpoint?

### ISSUE THREAD

**Issue by marwahmh** [skycrapers/TecoGAN-PyTorch#20]

**Comment by jndeng** [comment]
Hi, you can initialize the training with a pre-trained weight by setting the [load_path](https://github.com/skycrapers/TecoGAN-PyTorch/blob/master/experiments_BD/FRVSR/FRVSR_REDS_2xSR_2GPU/train.yml#L43) option in train.yml. But this is an ad-hoc solution and it cannot resume the training states.

**Comment by marwahmh** [comment]
> 

Hello, I tried this but it starts from epoch 0 too ... I don't know if it starts from the updated parameters or from the beginning.

**Comment by jndeng** [comment]
@marwahmh If you set the load_path, the training will start from that pre-trained model. Since we don't record the training states, 
 the logger has to start from 0.
