### ISSUE TITLE
Different resolutions in training data

### ISSUE THREAD

**Issue by Flemingjp** [skycrapers/TecoGAN-PyTorch#21]
Is there support for a mixed training set with GT videos of different resolution?

Also, can I provide my own LR videos rather than applying BI/BD?

**Comment by jndeng** [comment]
Hi, @Flemingjp 
1. Yes, mixed training set with different resolutions is supported.
2. You can use BI mode, and specify [gt_seq_dir](https://github.com/skycrapers/TecoGAN-PyTorch/blob/master/experiments_BI/FRVSR/FRVSR_VimeoTecoGAN_4xSR_2GPU/train.yml#L14) and [lr_seq_dir](https://github.com/skycrapers/TecoGAN-PyTorch/blob/master/experiments_BI/FRVSR/FRVSR_VimeoTecoGAN_4xSR_2GPU/train.yml#L15) to your own videos.

**Comment by Flemingjp** [comment]
@jndeng Awesome thank you!
