### ISSUE TITLE
Data set directory structure

### ISSUE THREAD

**Issue by mouxinyue1** [skycrapers/TecoGAN-PyTorch#22]
Hi, I would like to know what the catalog structure should look like when I switch to a REDS dataset

**Comment by jndeng** [comment]
Hi, the raw REDS dataset has the following structure:
```tex
data
  ├─ REDS
    ├─ Raw
      ├─ 000
        └─ ***.png
      ├─ 001
        └─ ***.png
      └─ ...
    └─ Bicubic2xLR        
      ├─ 000
        └─ ***.png
      ├─ 001
        └─ ***.png
      └─ ...
```
'Bicubic2xLR' is not necessary if you are using the BD degradation.

**Comment by mouxinyue1** [comment]
Thank you very much for your help
