### ISSUE TITLE
How to upscale our own videos?

### ISSUE THREAD

**Issue by Vermeille** [skycrapers/TecoGAN-PyTorch#23]
Hi,

What's the procedure to upscale our own videos? The current code seems to need ground truth results and computes metrics. What if I just want to try it on my own videos?

Thank you

**Comment by jndeng** [comment]
Hi, there's no interface for direct inference in the current code. The data loader needs to read a pair of low&high resolution videos. A simple way is to upscale your video using bilinear/bicubic interpolation and use it as the 'ground-truth'. After running the test code, you can just take the generated HR video and ignore those computed metrics.

BTW, I might write an interface for direct inference in next few weeks.
