### ISSUE TITLE
Seek train dataset

### ISSUE THREAD

**Issue by yinyiyu** [skycrapers/TecoGAN-PyTorch#3]
Thans for your great work. When I downloaded the training data set according to the instructions of TecoGAN-Tensoflow, there was a problem that the video could not be downloaded. Could you please upload it to the network disk and provide it for everyone to download? Thank you!

**Comment by jndeng** [comment]
Refer to issue #16.

We now support model training on the public REDS dataset, which can be readily downloaded. Please refer to the README for more details.
