### ISSUE TITLE
Resume training

### ISSUE THREAD

**Issue by IceClear** [skycrapers/TecoGAN-PyTorch#8]
Thanks for the nice code! I wonder if there are any settings for resuming from the checkpoint? Sometimes it could be a problem if the training process  breaks down unexpectedly.

**Comment by jndeng** [comment]
Thanks for you interest!

Unfortunately there's no resuming function in this code. I agree resuming could be very useful especially when training on large datasets. I think I'll add it in the future.

BTW, BasicSR provides a great example about this. You may refer to BasicSR if you currently need this function.
